### ISSUE TITLE
Delete function?

### ISSUE THREAD

**Issue by seodevse** [chatdoc-com/chatdoc-com.github.io#1]
Is this function not finished? https://api-reference.chatdoc.com/#tag/Documents/operation/Delete_Document_documents__upload_id__delete

Looks the same as 
https://api-reference.chatdoc.com/#tag/Documents/operation/Get_Document_documents__upload_id__get

**Comment by BoWuGit** [comment]
No, the http method is different, which is of [RESTful](https://en.wikipedia.org/wiki/REST) style.
