### ISSUE TITLE
Mix of language in output

### ISSUE THREAD

**Issue by seodevse** [chatdoc-com/chatdoc-com.github.io#2]
I request answers in Swedish, with an English prompt. 

Sometimes, like 1 out of 50, the answer is a mix of English and Swedish.

**Comment by BoWuGit** [comment]
Yes, we can't [promise](https://api-reference.chatdoc.com/#tag/Questions/operation/Ask_Question_questions_post), it relys on GPT's compatibility.

<img width="789" alt="图片" src="https://github.com/chatdoc-com/chatdoc-com.github.io/assets/6310246/9b6ac3f6-4bd1-40e8-91dd-ae4a553c4802">
