### ISSUE TITLE
Want to show markdown

### ISSUE THREAD

**Issue by dhyoum-turtle** [chatdoc-com/chatdoc-com.github.io#3]
Hello. I'm developer, who are using your apis.
I want to show my markdown documents via `DOCViewerSDK`, so I wrote codes below as written in your guides:
`sdk.open({
          url: "XXXXXX.md",
          viewerType: "html",
        });`
but in result, it only shows blank screen, with 200 response. 
What should I do?

**Comment by jiaxiaxia** [comment]
Markdown files cannot be displayed directly using the DOCViewerSDK. To resolve this, you can utilize the [Upload API](https://api-reference.chatdoc.com/#tag/Documents/operation/Upload_Document_documents_upload_post) to upload your Markdown file. Once uploaded, you'll receive an upload id. With this ID, you can construct the [Download URL](https://api-reference.chatdoc.com/#tag/Documents/operation/Download_Document_documents__upload_id__download_get) and pass it into the sdk.open method like this:

```
sdk.open({
  url: `https://your-service.com/documents/${uploadId}/download`,
  viewerType: "html"
});

```

**Comment by dhyoum-turtle** [comment]
Thank you for your reply.
But that method gives me a 403 error. 😢 
```
  <Code>AccessDenied</Code>
  <Message>You are denied by bucket referer policy.</Message>
```

**Comment by jiaxiaxia** [comment]
Could you specify which method is returning the 403 error? That way, I can help troubleshoot the issue more effectively. 😊 Also, please ensure that all API calls require [authentication](https://api-reference.chatdoc.com/#section/Introduction/Authentication).

**Comment by dhyoum-turtle** [comment]
<img width="330" alt="image" src="https://github.com/user-attachments/assets/81895e6e-25bc-4579-be5c-43ded63947fe">

As in the picture, when I call `documents/{upload_id}/download`([link](https://api-reference.chatdoc.com/#tag/Documents/operation/Download_Document_documents__upload_id__download_get)) , 307 and then 403 errors occur.  
Also, I always send authentication as well...

Below is the code I wrote.
```
sdk.open({
  url: await downloadDocument(uploadId),
  viewerType: "html",
});

---

export const downloadDocument = async (uploadId: string): Promise<string> => {
  try {
    const result = await axiosInstance.get<AxiosResponse>(
      `/documents/${uploadId}/download`
    );
    return result.request.responseURL;
  } catch (error) {
    const e = error as AxiosError;
    return e.request.responseURL;
  }
};
```
Now, even if an error occurs, the `responseURL` inside the `request` is used.
Is there anything wrong with my usage?

**Comment by BoWuGit** [comment]
We are sorry for this bug, we have scheduled to fix it in September, once fixed we would comment here, thanks for your attention.

**Comment by cumtyc** [comment]
Due to permission restrictions, we do not support direct file downloads from our API via a browser connection. Instead, similar to other interfaces, you can handle file downloads through server-side calls.

**Comment by dhyoum-turtle** [comment]
Thank you for providing the solution!
Fortunately, there was no error when calling from the server-side. (It works to me!)

Now that it's resolved, I'll close the issue. thank you. 😄
