### ISSUE TITLE
Markdown HTML Issue

### ISSUE THREAD

**Issue by spseon** [chatdoc-com/chatdoc-com.github.io#5]
Hello, there is a markdown format issue. 

- ChatDoc is able to display symbols(bullet points, numbers) from markdown text. 
<img width="784" alt="스크린샷 2024-10-11 오후 11 21 41" src="https://github.com/user-attachments/assets/0a64bde6-4494-476f-a118-42bac80b298d">

- But when we upload the same file to custom API, the symbols disappear. 
<img width="817" alt="스크린샷 2024-10-11 오후 11 22 52" src="https://github.com/user-attachments/assets/f133c18a-da42-4006-9553-03a823754ffd">

Is there a way to keep the symbols?

**Comment by spseon** [comment]
Below is a sample markdown text we used: 

[Markdown Test File for Symbils.md](https://github.com/user-attachments/files/17343997/Markdown.Test.File.for.Symbils.md)

**Comment by jiaxiaxia** [comment]
Sorry, this is a bug in the SDK. We will fix it as soon as possible and notify you

**Comment by jiaxiaxia** [comment]
The issue has been fixed. You just need to refresh the page to see the changes

**Comment by spseon** [comment]
We checked and it works well :) Thank you!
